/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stm32f401re.h>
#include "stm32f401re_rcc.h"
#include "stm32f401re_gpio.h"

/* Button logic (PB3 Pull-Up): nhấn = 0, nhả = 1 */
#define BUTTON_PRESS     0
#define BUTTON_RELEASE   1

/* LED GREEN: PA0 */
#define LED_GPIO_PORT        GPIOA
#define LED_GPIO_PIN         GPIO_Pin_0
#define LED_GPIO_CLOCK_EN    RCC_AHB1Periph_GPIOA

/* BUZZER: PC9 */
#define BUZZER_GPIO_PORT        GPIOC
#define BUZZER_GPIO_PIN         GPIO_Pin_9
#define BUZZER_GPIO_CLOCK_EN    RCC_AHB1Periph_GPIOC

/* BUTTON B2: PB3 */
#define BUTTON_GPIO_PORT        GPIOB
#define BUTTON_GPIO_PIN         GPIO_Pin_3
#define BUTTON_GPIO_CLOCK_EN    RCC_AHB1Periph_GPIOB

/* Function prototypes */
static void mainInit(void);
static void led_Init(void);
static void buzzer_Init(void);
static void buttonB2_Init(void);

int main(void)
{
    mainInit();

    while (1)
    {
        /* Đọc trạng thái nút B2 */
        if (GPIO_ReadInputDataBit(BUTTON_GPIO_PORT, BUTTON_GPIO_PIN) == BUTTON_PRESS)
        {
            /* Nhấn */
            GPIO_SetBits(LED_GPIO_PORT, LED_GPIO_PIN);
            GPIO_SetBits(BUZZER_GPIO_PORT, BUZZER_GPIO_PIN);
        }
        else
        {
            /* Nhả */
            GPIO_ResetBits(LED_GPIO_PORT, LED_GPIO_PIN);
            GPIO_ResetBits(BUZZER_GPIO_PORT, BUZZER_GPIO_PIN);
        }
    }
}

static void mainInit(void)
{
    led_Init();
    buzzer_Init();
    buttonB2_Init();
}

static void led_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;

    RCC_AHB1PeriphClockCmd(LED_GPIO_CLOCK_EN, ENABLE);

    GPIO_InitStructure.GPIO_Pin   = LED_GPIO_PIN;
    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_OUT;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
    GPIO_InitStructure.GPIO_PuPd  = GPIO_PuPd_DOWN;
    GPIO_Init(LED_GPIO_PORT, &GPIO_InitStructure);

    GPIO_ResetBits(LED_GPIO_PORT, LED_GPIO_PIN);
}

static void buzzer_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;

    RCC_AHB1PeriphClockCmd(BUZZER_GPIO_CLOCK_EN, ENABLE);

    GPIO_InitStructure.GPIO_Pin   = BUZZER_GPIO_PIN;
    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_OUT;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
    GPIO_InitStructure.GPIO_PuPd  = GPIO_PuPd_UP;
    GPIO_Init(BUZZER_GPIO_PORT, &GPIO_InitStructure);

    GPIO_ResetBits(BUZZER_GPIO_PORT, BUZZER_GPIO_PIN);
}

static void buttonB2_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;

    RCC_AHB1PeriphClockCmd(BUTTON_GPIO_CLOCK_EN, ENABLE);

    GPIO_InitStructure.GPIO_Pin  = BUTTON_GPIO_PIN;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;
    GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
    GPIO_Init(BUTTON_GPIO_PORT, &GPIO_InitStructure);
}
